title: Computing in Context - Kay Shibata
author: Kay Shibata

only_build_toc_files: true

execute:
  execute_notebooks: "off"

sphinx:
  config:
    myst_heading_anchors: 4
    html_js_files:
      - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    suppress_warnings: ["mystnb.unknown_mime_type"]
